apiVersion: v1
kind: Service
metadata:
  name: agri-platform-backend-service
  labels:
    app: agri-platform-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: agri-platform-backend
  sessionAffinity: None 