apiVersion: apps/v1
kind: Deployment
metadata:
  name: slam-frontend
  labels:
    app: slam-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: slam-frontend
  template:
    metadata:
      labels:
        app: slam-frontend
    spec:
      containers:
      - name: slam-frontend
        image: gcr.io/PROJECT_ID/slam-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://slam-backend-service"
        - name: NEXT_PUBLIC_AUTH_ENABLED
          value: "true"
        - name: NODE_ENV
          value: "production"
        - name: CONTACT_EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: slam-secrets
              key: CONTACT_EMAIL_PASS
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      imagePullSecrets:
      - name: gcr-secret 