# General-purpose Cloud Build config for Dockerized Next.js app
# Usage: Set _SERVICE and _REGION substitutions in your trigger or use defaults below

substitutions:
  _SERVICE: "slam-website"   # Default Cloud Run service name
  _REGION: "us-central1"     # Default region

steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/nextjs-slam:$SHORT_SHA', '.' ]

  # Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/nextjs-slam:$SHORT_SHA' ]

  # Deploy to Cloud Run (service and region can be overridden)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', '$_SERVICE',
        '--image', 'gcr.io/$PROJECT_ID/nextjs-slam:$SHORT_SHA',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/nextjs-slam:$SHORT_SHA' 
  #hello