# SLAM Robotics - Optimized Cloud Build for Cloud Run
# Deploys frontend (Next.js) and backend (FastAPI) to Cloud Run

substitutions:
  _FRONTEND_SERVICE: "slam-frontend"
  _BACKEND_SERVICE: "slam-backend"
  _REGION: "us-central1"
  _GMAIL_APP_PASSWORD: "rgeu ouzv ebeb borr"

steps:
  # Build Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA', '.' ]

  # Build Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA', '-f', 'backend/Dockerfile', './backend' ]

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA' ]

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', '$_BACKEND_SERVICE',
        '--image', 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8000',
        '--memory', '512Mi',
        '--cpu', '1',
        '--max-instances', '10',
        '--set-env-vars', 'DATABASE_URL=sqlite:///./agri_platform.db,SECRET_KEY=your-production-secret-key-change-this,JWT_SECRET=your-jwt-secret-change-this,CONTACT_EMAIL_PASS=$_GMAIL_APP_PASSWORD'
      ]

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', '$_FRONTEND_SERVICE',
        '--image', 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '3000',
        '--memory', '512Mi',
        '--cpu', '1',
        '--max-instances', '10',
        '--set-env-vars', 'NEXT_PUBLIC_API_URL=https://$_BACKEND_SERVICE-$PROJECT_ID-$_REGION.a.run.app/api,NEXT_PUBLIC_AUTH_ENABLED=true,NODE_ENV=production,CONTACT_EMAIL_PASS=$_GMAIL_APP_PASSWORD'
      ]

  # Get service URLs for output
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'services', 'describe', '$_BACKEND_SERVICE',
        '--region', '$_REGION',
        '--format=value(status.url)'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'services', 'describe', '$_FRONTEND_SERVICE',
        '--region', '$_REGION',
        '--format=value(status.url)'
      ]

images:
  - 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA'
