# Backend-only Cloud Build config for Agriculture Platform
# Deploys only the backend service

substitutions:
  _BACKEND_SERVICE: "agriculture-backend"   # Backend service name
  _REGION: "us-central1"     # Default region

steps:
  # Build Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/agriculture-backend:$SHORT_SHA', '-f', 'backend/Dockerfile', './backend' ]

  # Push Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/agriculture-backend:$SHORT_SHA' ]

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', '$_BACKEND_SERVICE',
        '--image', 'gcr.io/$PROJECT_ID/agriculture-backend:$SHORT_SHA',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--set-env-vars', 'DATABASE_URL=sqlite:///./agri_platform.db,SECRET_KEY=your-production-secret-key,ALGORITHM=HS256,ACCESS_TOKEN_EXPIRE_MINUTES=30,HOST=0.0.0.0,PORT=8000,DEBUG=false,ALLOWED_ORIGINS=["https://slam-website-us-central1.a.run.app"]'
      ]

images:
  - 'gcr.io/$PROJECT_ID/agriculture-backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 