# SLAM Robotics Cloud Run Deployment - CHEAPEST!
# Deploys both frontend and backend to Cloud Run

substitutions:
  _REGION: "us-central1"
  _GMAIL_APP_PASSWORD: "rgeu ouzv ebeb borr"

steps:
  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA', '.' ]

  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA', '-f', 'backend/Dockerfile', './backend' ]

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA' ]

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA' ]

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'slam-frontend',
        '--image', 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '3000',
        '--memory', '512Mi',
        '--cpu', '1',
        '--max-instances', '10',
        '--set-env-vars', 'NEXT_PUBLIC_API_URL=https://slam-backend-xyz123-uc.a.run.app'
      ]

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'slam-backend',
        '--image', 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA',
        '--region', '$_REGION',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8000',
        '--memory', '1Gi',
        '--cpu', '1',
        '--max-instances', '10',
        '--set-env-vars', 'DATABASE_URL=sqlite:///./agri_platform.db,SECRET_KEY=your-production-secret-key-change-this,JWT_SECRET=your-jwt-secret-change-this,CONTACT_EMAIL_PASS=$_GMAIL_APP_PASSWORD'
      ]

  # Get service URLs
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'services', 'list',
        '--region', '$_REGION',
        '--format', 'table(name,status.url)'
      ]

images:
  - 'gcr.io/$PROJECT_ID/slam-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/slam-backend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY