# SLAM Robotics - Cloud Build for Cloud Run
# Deploys frontend (Next.js) and backend (FastAPI) to Cloud Run

substitutions:
  _FRONTEND_SERVICE: "slam-frontend"
  _BACKEND_SERVICE: "slam-backend"
  _REGION: "us-central1"
  _GMAIL_APP_PASSWORD: "rgeu ouzv ebeb borr"

options:
  logging: CLOUD_LOGGING_ONLY
  # defaultLogsBucket: gs://slam-website-466808_cloudbuild

steps:
  # Build Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/slam-frontend:latest', '.' ]

  # Build Backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/slam-backend:latest', '-f', 'backend/Dockerfile', './backend' ]

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/slam-frontend:latest' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/slam-backend:latest' ]

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'slam-backend',
        '--image', 'gcr.io/$PROJECT_ID/slam-backend:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8000',
        '--memory', '512Mi',
        '--cpu', '1',
        '--max-instances', '10',
        '--set-env-vars', 'DATABASE_URL=sqlite+aiosqlite:////app/agri_platform.db,SECRET_KEY=your-production-secret-key-change-this,JWT_SECRET=your-jwt-secret-change-this,CONTACT_EMAIL_PASS=rgeu ouzv ebeb borr'
      ]

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', 'slam-frontend',
        '--image', 'gcr.io/$PROJECT_ID/slam-frontend:latest',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '3000',
        '--memory', '512Mi',
        '--cpu', '1',
        '--max-instances', '10',
        '--set-env-vars', 'NEXT_PUBLIC_API_URL=https://slam-backend-$PROJECT_ID-us-central1.a.run.app/api,NEXT_PUBLIC_AUTH_ENABLED=true,NODE_ENV=production,CONTACT_EMAIL_PASS=rgeu ouzv ebeb borr'
      ]

  # Get service URLs for output
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'services', 'describe', '$_BACKEND_SERVICE',
        '--region', '$_REGION',
        '--format=value(status.url)'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'services', 'describe', '$_FRONTEND_SERVICE',
        '--region', '$_REGION',
        '--format=value(status.url)'
      ]

images:
  - 'gcr.io/$PROJECT_ID/slam-frontend:latest'
  - 'gcr.io/$PROJECT_ID/slam-backend:latest'
