steps:
  # Build and push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/agriculture-backend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/agriculture-backend:latest',
      '-f', 'backend/Dockerfile',
      './backend'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agriculture-backend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agriculture-backend:latest']

  # Build and push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/agriculture-frontend:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/agriculture-frontend:latest',
      '-f', 'Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agriculture-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agriculture-frontend:latest']

  # Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'container', 'clusters', 'get-credentials',
      'agriculture-cluster',
      '--zone', 'us-central1-a',
      '--project', '$PROJECT_ID'
    ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 'image',
      'deployment/agriculture-backend',
      'agriculture-backend=gcr.io/$PROJECT_ID/agriculture-backend:$COMMIT_SHA'
    ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 'image',
      'deployment/agriculture-frontend',
      'agriculture-frontend=gcr.io/$PROJECT_ID/agriculture-frontend:$COMMIT_SHA'
    ]

  # Update secrets
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'create', 'secret', 'generic', 'agriculture-secrets',
      '--from-literal=DATABASE_URL=$_DATABASE_URL',
      '--from-literal=SECRET_KEY=$_SECRET_KEY',
      '--from-literal=JWT_SECRET=$_JWT_SECRET',
      '--dry-run=client', '-o=yaml'
    ] | kubectl apply -f -

  # Wait for deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'rollout', 'status',
      'deployment/agriculture-backend'
    ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'rollout', 'status',
      'deployment/agriculture-frontend'
    ]

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Substitutions
substitutions:
  _DATABASE_URL: 'postgresql://user:pass@host:5432/db'
  _SECRET_KEY: 'your-secret-key'
  _JWT_SECRET: 'your-jwt-secret'

# Timeout
timeout: '1200s' 